### ISSUE TITLE
Add filter by name

### ISSUE THREAD

**Issue by Namanl2001** [Namanl2001/MERN-Gurujii-dev#10]
After filtering data for a particular pin-code, a filter to search profile by teacher's name could be useful, at the user end.

**Comment by subhangi2731** [comment]
can you please assign this issue to me?

**Comment by Namanl2001** [comment]
@subhangi2731 would you be able to work on all three issues together? My advice would be to start small by picking one/two issues according to your interests. Thanks!

**Comment by Namanl2001** [comment]
@subhangi2731 you can take up this issue. Let us know if you have any queries.

**Comment by Namanl2001** [comment]
@subhangi2731 are you working on this? Facing any issue? If any feel free to communicate with mentors on the discord project channel.

**Comment by subhangi2731** [comment]
@Namanl2001 Yes I am working on this issue will make a pr by tomorrow but I have a doubt how can I reach u??

**Comment by subhangi2731** [comment]
Can you tell me is there any different server for this project or can you just tell me ur discord username??

**Comment by Namanl2001** [comment]
> @Namanl2001 Yes I am working on this issue will make a pr by tomorrow but I have a doubt how can I reach u??
> 

If you are a gssoc participant then Discord project channel.

**Comment by subhangi2731** [comment]
@Namanl2001 Do I have to use the excel filtering approach and search the teachers name ??

**Comment by subhangi2731** [comment]
By using sorting and  filter group??

**Comment by Namanl2001** [comment]
Acc. to GSSoC guidelines contributors shouldn't be given more than 7 days so that other participants can also contribute. So are you working on this? FYI now it's 17 days you are assigned to this.

**Comment by sagar-barapatre** [comment]
@ChitvanRamani22 wanna take this up ? If you need guidance for this you can ask me

**Comment by ChitvanRamani22** [comment]
@sagar-barapatre yes i am interested, but might need some help.

**Comment by sagar-barapatre** [comment]
Okay you can ask me on discord.

> @sagar-barapatre yes i am interested, but might need some help.

**Comment by sagar-barapatre** [comment]
#162 PR has been already made for this. So those who wanted to contribute on this can review the PR and suggest something they want to add. Thnx

**Comment by Namanl2001** [comment]
closing via #162
