### ISSUE TITLE
Add spinner

### ISSUE THREAD

**Issue by Namanl2001** [Namanl2001/MERN-Gurujii-dev#101]
**Describe the feature you'd like to be added**
A spinner/loader gif could be added in place of `initializing data` [here](https://github.com/Namanl2001/MERN-Gurujii-dev/blob/802725c21bc5ce640177b717a54421cea6afe790/src/components/home.jsx#L48).

**Comment by DineshKoushik** [comment]
Hi @Namanl2001 ,
Let me take over this issue. I guess, I can help you with this.

**Comment by DineshKoushik** [comment]
@Namanl2001 Hi again, please verify the pull request I created, go through the updates made. If possible give feedback as well, if I missed out something. Thank you.

**Comment by Muditxofficial** [comment]
@Namanl2001 Can i work on this issue

**Comment by Muditxofficial** [comment]
@Namanl2001 bootstrap-4-react does not have inbuilt spinner,should i create from css or use their progress components which looks like this.
![progress](https://user-images.githubusercontent.com/63860014/114302971-34deb480-9ae9-11eb-9f13-145370a5a8b5.png)

**Comment by Namanl2001** [comment]
> 
> 
> @Namanl2001 bootstrap-4-react does not have inbuilt spinner,should i create from css or use their progress components which looks like this.
> ![progress](https://user-images.githubusercontent.com/63860014/114302971-34deb480-9ae9-11eb-9f13-145370a5a8b5.png)

Sure you can use this but decrease the width to make it more attractive and also if you like you can add some heading above the bar saying "initializing data".

**Comment by Muditxofficial** [comment]
https://user-images.githubusercontent.com/63860014/114338572-f68cd800-9b70-11eb-8880-0019163d27dc.mp4
Changes made per request.

**Comment by Namanl2001** [comment]
Nice please make a PR. But don't forget to customize it for the mobile phone too. Also, add screenshots from both laptop and mobile after final changes.
