### ISSUE TITLE
Add Ms. option in teacher profile form

### ISSUE THREAD

**Issue by AakankshaShah** [Namanl2001/MERN-Gurujii-dev#105]
**Describe the bug**
Currently we only have two options-Mr. & Mrs. I would like to add Ms.(miss) option to cover all possible cases.

**Comment by ChitvanRamani22** [comment]
@Namanl2001 @sagar-barapatre if bo body is working on it i am interested in taking this.

**Comment by AakankshaShah** [comment]
@ChitvanRamani22  I am already working on it.

**Comment by ChitvanRamani22** [comment]
Okay @AakankshaShah i thought that i has been opened 12 days ago so you might not be working on it.
