### ISSUE TITLE
Input Form Validation and Feedback

### ISSUE THREAD

**Issue by ssaksham** [Namanl2001/MERN-Gurujii-dev#107]
Right now, the create/ update form does not give any feedback to the user about the input requirements. If the user is not able to fulfill the requirements, the user just got redirected to the main giving no information about the unsuccessful submission.

My idea is to show the user, what the user is missing and only on filling these requirements, the submission could be made, just like below:
![image](https://user-images.githubusercontent.com/41958505/112602110-482b2800-8e39-11eb-8d9b-47068e1c6d44.png)

If you like this approach kindly assign this to me.

**Comment by Namanl2001** [comment]
Thanks for opening this issue, this was under the agenda.

**Comment by Jassi10000** [comment]
Being a GSSOC'21 participant I also want to try my hands onto this . Can you assign this to me  too @Namanl2001 ,

**Comment by sagar-barapatre** [comment]
@ssaksham are you working on that ? Or else shall we assign it to @Jassi10000

**Comment by ssaksham** [comment]
I am working.

**Comment by tend2infinity** [comment]
Hey @Namanl2001 I would like to work on this issue

**Comment by Jassi10000** [comment]
@sagar-barapatre Can you please assign me , I asked for this long time ago

**Comment by Jassi10000** [comment]
thanks @Namanl2001 for assigning , will try my best to solve this

**Comment by sagar-barapatre** [comment]
@Jassi10000 it's been a long time. Any help required ?

**Comment by ChitvanRamani22** [comment]
@sagar-barapatre if @Jassi10000 is not working on this i would like to take this up.
