### ISSUE TITLE
Footer improvement

### ISSUE THREAD

**Issue by ChitvanRamani22** [Namanl2001/MERN-Gurujii-dev#108]
Footer in our website is too huge which is rarely seen and also it would look attractive if we add some font awesome icons of github, linkedin, instagram etc.
If you like this idea please do assign it to me.

**Comment by ChitvanRamani22** [comment]
@sagar-barapatre  Yeah i have made the footer but waiting for my previous pr #113 to get merged else they will get piled up.

**Comment by Namanl2001** [comment]
closing via #117
