### ISSUE TITLE
Add filter for Home/External tutor.

### ISSUE THREAD

**Issue by Namanl2001** [Namanl2001/MERN-Gurujii-dev#111]
**Describe the feature you'd like to add**
It would be nice to have a filter for the Home/External tutors.

**Additional context**
Same as other filters

**Comment by akshay1027** [comment]
i would like to work on this!

**Comment by akshay1027** [comment]
@Namanl2001 am unable yo login i guess, can you please help me out

**Comment by sagar-barapatre** [comment]
DM me in the project's discord channel to get your doubt solved.

**Comment by akshay1027** [comment]
I have sent message @sagar-barapatre

**Comment by akshay1027** [comment]
The home/external filter on its own is working properly! home/external filter with classes is also working properly, but home/external filter with subjects is not working as i wanted too! someone help me out in this! @sagar-barapatre @Namanl2001 . I have tried my best! i think the the problem lies along those lines, please check it out:

![2021-04-08 (2)_LI](https://user-images.githubusercontent.com/65683151/113949248-70008f80-982c-11eb-9f59-247ffea21650.jpg)

**Comment by Namanl2001** [comment]
@akshay1027 are you working on this?

**Comment by akshay1027** [comment]
yea please check the PR, home/external filter alone, and with classes, the filter is working perfectly!

**Comment by Namanl2001** [comment]
What do you mean by "alone and with classes"?

**Comment by ChitvanRamani22** [comment]
@Namanl2001 if nobody is working on this i would like to take this up.

**Comment by ChitvanRamani22** [comment]
@Namanl2001 if no one is working on this issue, I would like to take this up.

**Comment by Namanl2001** [comment]
@akshay1027 has already opened a PR for this issue but he is facing some problems would be nice if you can help him.
PS: points will be awarded to both of you. Thanks

**Comment by akshay1027** [comment]
@ChitvanRamani22 , here is the PR #122 . please pull this code in your forked repo and check it out! Half of the work is done but i don't know how to combine subject filter and tutor filter! would be great if you can help me out! Thank you! 
here is the video showing my problem https://drive.google.com/file/d/1GrkY-KRc_zjPyCCKfSRp_DXjJHKdWcmP/view?usp=sharing

**Comment by tend2infinity** [comment]
hey @akshay1027 I will review your PR and tell you some of the changes that may fix this issue

**Comment by ChitvanRamani22** [comment]
@Namanl2001 if this issue is still open i would like to take this up.
