### ISSUE TITLE
Animation in cards view

### ISSUE THREAD

**Issue by Namanl2001** [Namanl2001/MERN-Gurujii-dev#12]
I was thinking of some animation which zooms from 0% to 100%. If you have any other animation idea feel free to discuss.

**Comment by ChitvanRamani22** [comment]
@Namanl2001 I would like to work on this issue .Can you please assign this to me as a part of GSSOC'21.

**Comment by Namanl2001** [comment]
Thanks! @ChitvanRamani22 for your interest. Feel free to take up this issue.

**Comment by ChitvanRamani22** [comment]
Okay @Namanl2001 thankyou for assigning me this issue. I have signed up the NDA form now I will start working on it.

**Comment by maanpatel2492** [comment]
I can work on this issue.Assign me if possible.
(under GSSOC'21)

**Comment by ChitvanRamani22** [comment]
@Namanl2001 I am facing this problem while running the server
Can you please help me out.
![a70a16c1-70cc-408b-a7af-8ab91969cab3](https://user-images.githubusercontent.com/68965499/109770817-0c2dea00-7c22-11eb-86a0-16ef1bc9a9d3.jpg)

**Comment by Namanl2001** [comment]
This is because you don't have the username and password credentials of the main database, as due to security reasons i have made them private.
For using it you could use MongoDb locally and update the uri accordingly.

**Comment by ChitvanRamani22** [comment]
@Namanl2001 I had setup the project and it is running on my pc after which I tried to make some changes but none of them is working.
Ex. In the ss shown here i changed the width of card from 20em to 2em to see is it working or not, but the cards appeared in same fashion as earlier.
Can you please help me. 

![Screenshot (448)](https://user-images.githubusercontent.com/68965499/110238521-1aed0780-7f68-11eb-8e23-378190ed5e08.png)

**Comment by Namanl2001** [comment]
are you reloading the webpage after each change?

**Comment by ChitvanRamani22** [comment]
Yes tried it many times
Also i tried restarting the server after doing changes but couldn't observe any of the changes.

**Comment by Ankita297** [comment]
Can i work on this issue ?

**Comment by ChitvanRamani22** [comment]
@Namanl2001 I have find out the way of how to apply a good animation and also tried it on rough basis but can you please help me regarding my query that I earlier posted, as any of the changes are not being displayed.

**Comment by Namanl2001** [comment]
@Ankita297 as Chitvan is already working on this issue let's wait for him, to prevent duplicate efforts. Till then you can pick some other issue in this project. Thanks for your interest.

@ChitvanRamani22 I just saw [here](https://github.com/Namanl2001/MERN-Gurujii-dev/issues/12#issuecomment-789511866) that you are running `yarn server` which will only start the backend server. But in [Readme.md](https://github.com/Namanl2001/MERN-Gurujii-dev/blob/master/README.md) I've already mentioned `yarn dev` which starts the frontend at `localhost:3000` and backend at `localhost:5000`. Try it and let me know if you have other questions.

**Comment by nikhil-Vaibhav** [comment]
Hello @Namanl2001 I want to work on this issue under GSSoC'21. I have even started visualizing this. Please assign this to me.
Thanks  a lot.

**Comment by dsnehasish74** [comment]
As this issue is not solved yet then I can solve this issue.  So can I solve this as a part of GSSOC 21
