### ISSUE TITLE
The UI of the card can be improved

### ISSUE THREAD

**Issue by akshay1027** [Namanl2001/MERN-Gurujii-dev#123]
**Describe the bug**
The UI of the card can be improved. EG: changing colour of card to a darker version (instead of grey) to match other colours in the website.

**Comment by sagar-barapatre** [comment]
The PR #113 has been already made for this.. So you suggest or review that PR if you want to do so

**Comment by akshay1027** [comment]
I would love to do that! But there is no screenshot of the changes, maybe I will try to set up his branch and let you know! But I cant make changes right? i need permission to make review?

**Comment by Namanl2001** [comment]
@akshay1027 you can pull the changes of that pr to view and make any other changes. And feel free to comment your thoughts/changes on the pr itself. 
PS: Anyone can review any pr on github, no permission is required for that purpose. Thanks.

**Comment by akshay1027** [comment]
The Address is going out of the card boundary, That is the only issue in the new card design as of now. So shall I make those changes? 

![2021-04-02 (8)](https://user-images.githubusercontent.com/65683151/113437924-2f0c1380-9405-11eb-82e5-f4f871a6e549.png)

**Comment by ChitvanRamani22** [comment]
@Namanl2001 can you please check your discord account i had sent u the vedio as i had created new UI for cards as u asked.
Can you please check and revert back

**Comment by guptaji6489** [comment]
> shall I make those

ya sure

**Comment by sagar-barapatre** [comment]
Actually this UI for the card is not taken. #130 has been made for this. On that PR you can add your review if you want to.
