### ISSUE TITLE
demo link to open in new tab

### ISSUE THREAD

**Issue by akshay1027** [Namanl2001/MERN-Gurujii-dev#126]
demo link(in readme) to open in a new tab so that users can easily navigate back to the codebase.

**Comment by sagar-barapatre** [comment]
I think they have the option to open the link in new tab by right clicking the link and selecting Open in new Tab. right ? 
I dnt think this should be considered as an issue.

**Comment by akshay1027** [comment]
cool, also found out now that we can't do this on Github! here is the link to that: mojombo/github-flavored-markdown#28
so I will close this.
