### ISSUE TITLE
Splash Screen addition

### ISSUE THREAD

**Issue by AakankshaKamal** [Namanl2001/MERN-Gurujii-dev#132]
**Describe the feature you'd like to add**
We could add an interactive splash screen just before opening the home page ,it will look good.

**Comment by guptaji6489** [comment]
Can you send me some demo ?

**Comment by guptaji6489** [comment]
What type of an interactive splash screen

**Comment by AakankshaKamal** [comment]
I was thinking like instead of direct opening the home page a splash screen could look better at the beginning ,something like 
shown here.
![demo](https://user-images.githubusercontent.com/58944717/114126121-6d2d9980-9915-11eb-9128-b10d736f2982.gif)

**Comment by AakankshaKamal** [comment]
https://user-images.githubusercontent.com/58944717/114208455-1eb2e600-997b-11eb-8245-183a4c5f713a.mp4

Please do have a look on it .

**Comment by guptaji6489** [comment]
Looking Great.
Any suggestion @sagar-barapatre

**Comment by guptaji6489** [comment]
can you show something with light color in background?

**Comment by AakankshaKamal** [comment]
@guptaji6489  ok sir I'll change the background color to something light

**Comment by AakankshaKamal** [comment]
https://user-images.githubusercontent.com/58944717/114443229-11039780-9beb-11eb-8a21-185957e7a23a.mp4

**Comment by guptaji6489** [comment]
>  demo2.mp4

looking good

**Comment by AakankshaKamal** [comment]
Can I go ahead with PR?

**Comment by guptaji6489** [comment]
Any other suggestion  @Namanl2001  @sagar-barapatre. 
Or its look good?

**Comment by Namanl2001** [comment]
I think something simple would look more cool. The current one is nice but it has too many animations which IMO are not needed. thanks

**Comment by AakankshaKamal** [comment]
Ok I ll make the changes.

**Comment by AakankshaKamal** [comment]
https://user-images.githubusercontent.com/58944717/115261031-e9fc1700-a150-11eb-92b7-95d635234c0a.mp4

What about this?

**Comment by guptaji6489** [comment]
>  Gurujii.com.-.Profile.1.-.Microsoft.Edge.2021-04-19.20-49-54.mp4 
> What about this?

can you remove this text and also remove these two corners watch something and make it only simple by putting only one watch at the middle.

**Comment by AakankshaKamal** [comment]
ok sure

**Comment by AakankshaKamal** [comment]
![Screenshot 2021-04-19 212856](https://user-images.githubusercontent.com/58944717/115267017-562d4980-a156-11eb-9356-58dc3f9277df.png)
Look at this.

**Comment by guptaji6489** [comment]
> ![Screenshot 2021-04-19 212856](https://user-images.githubusercontent.com/58944717/115267017-562d4980-a156-11eb-9356-58dc3f9277df.png)
> Look at this.

not watch.
in the previous video whatever  is in the corner can you put in the middle

**Comment by AakankshaKamal** [comment]
The watch will be moving so I guess it ll look better

**Comment by guptaji6489** [comment]
which one you r taking about?

**Comment by AakankshaKamal** [comment]
https://user-images.githubusercontent.com/58944717/115269202-b3c29580-a158-11eb-95eb-8fb98fb8251e.mp4
Check this one Sir

**Comment by guptaji6489** [comment]
>  Gurujii.com.-.Profile.1.-.Microsoft.Edge.2021-04-19.20-49-54.mp4 
> What about this?

in this can you remove all things and simply put at the middle corner watch which is continuously moving

**Comment by guptaji6489** [comment]
> https://user-images.githubusercontent.com/58944717/115269202-b3c29580-a158-11eb-95eb-8fb98fb8251e.mp4
> Check this one Sir

**Comment by guptaji6489** [comment]
>  Gurujii.com.-.Profile.1.-.Microsoft.Edge.2021-04-19.20-49-54.mp4 
> What about this?

in this can you remove all things.
and in the corner (top left ), there are two lines that are continuously moving.
can you put that in the middle and nothing else , please
Read this carefully.

**Comment by AakankshaKamal** [comment]
![Screenshot 2021-04-25 171648](https://user-images.githubusercontent.com/58944717/115992209-19e06a00-a5ea-11eb-8894-f1e0c7e0b177.png)
This one?

**Comment by Namanl2001** [comment]
@ChitvanRamani22 If you are interested feel free to rake this up. thanks
