### ISSUE TITLE
The placeholder at the "Filter by pincode" section is not completely visible

### ISSUE THREAD

**Issue by tend2infinity** [Namanl2001/MERN-Gurujii-dev#138]
**Describe the bug**
The placeholder used at the place of the filter is not completely visible which is bad for UI.

**Screenshots**
![guruji-bug1](https://user-images.githubusercontent.com/61948033/114228669-6db94500-9994-11eb-834d-6d01f29fb463.JPG)

As a gssoc participant, I would like to work on this issue.

**Comment by sagar-barapatre** [comment]
The PR #136 has been made for this.

**Comment by Namanl2001** [comment]
yes, @tend2infinity you are right please go ahead. The pr @sagar-barapatre mentioned is not for this issue.
