### ISSUE TITLE
Add another filter which filters between "Home Tutor" and "External Tutor"

### ISSUE THREAD

**Issue by tend2infinity** [Namanl2001/MERN-Gurujii-dev#139]
**Describe the feature you'd like to add**
We already have filters related to the subject and class but maybe some students want to sort the tutors based upon Home or External Tutor. I want to add this functionality by creating another filter just like the previous ones.

**Describe how you will do it**
There's a reducer in this application so I will create another case for the reducer in which I can update the global state by filtering only those tutors in the global state that matches with the filter

**Comment by Namanl2001** [comment]
Already there #111 If no one is on that issue then feel free to take it up. Thanks!

**Comment by akshay1027** [comment]
@tend2infinity I have already made a PR for this, but am unable to combine the subject filter and home/external tutor filter! check this video for more info https://drive.google.com/file/d/1GrkY-KRc_zjPyCCKfSRp_DXjJHKdWcmP/view?usp=sharing.
Here is my PR #122, if you can solve this problem, please do it! i would be grateful for that
