### ISSUE TITLE
error on running the application on local machine

### ISSUE THREAD

**Issue by rishabhborn2win** [Namanl2001/MERN-Gurujii-dev#140]
**Describe the bug**
ypeError: undefined is not an object (evaluating 'text.length')

**Expected behavior**
It should initialise the data at the very first time.

**Screenshots**
<img width="1069" alt="Screenshot 2021-04-10 at 4 15 19 PM" src="https://user-images.githubusercontent.com/55771529/114267180-f4633600-9a17-11eb-8db4-4c442ea1969f.png">

**Additional context**
Please help me out.

**Comment by Namanl2001** [comment]
When this error is coming? on running the port? or on clicking somewhere?

**Comment by rishabhborn2win** [comment]
> When this error is coming? on running the port? or on clicking somewhere?

Instantly when we start the application by yarn dev

**Comment by Namanl2001** [comment]
This is not due to the code bug; might be some other problem. Have you tried to solve this? or google searched  it?

**Comment by rishabhborn2win** [comment]
> This is not due to the code bug; might be some other problem. Have you tried to solve this? or google searched it?

Yes but nothing helpful discovered..

**Comment by Namanl2001** [comment]
Head to the discord's project channel to discuss it with the mentors. As this issue is only with your machine. thanks

**Comment by sagar-barapatre** [comment]
@rishabhborn2win buddy message me on discord. I'll help you out.

**Comment by Namanl2001** [comment]
If your issue is resolved then we can close this. And please mention the solution so that if it is from our side then we can remove that bug.

**Comment by sagar-barapatre** [comment]
Is your query solved ? Shall we close this ?

**Comment by rishabhborn2win** [comment]
> If your issue is resolved then we can close this. And please mention the solution so that if it is from our side then we can remove that bug.

I am sorry I was quite busy in some other issues Its resolved thank for your support!
