### ISSUE TITLE
Project not running on local machine

### ISSUE THREAD

**Issue by Jassi10000** [Namanl2001/MERN-Gurujii-dev#149]
Am not able to start the project on my local machine  even after installing the dependencies and following the exact guidelines in the readme , wanna ask that is the project not compatible for latest version of Node ?

Here's a scrennshot of the issue am facing 
![gurujiDoubt](https://user-images.githubusercontent.com/64856348/114820715-11fc1b00-9ddd-11eb-9e7a-751f9f5624f0.PNG)

**Comment by Namanl2001** [comment]
can you please try doing ">=12.14.0" [here](https://github.com/Namanl2001/MERN-Gurujii-dev/blob/a453f7994418dd4f74c945ddbb3e14d21429fa27/backend/package.json#L26) and restarting the server.
BTW have you faced any problem with `yarn dep0` and `yarn dep1` commands?

**Comment by sagar-barapatre** [comment]
Okay you can ask on me on discord. I think its only on your machine that error is coming. Anyways I'll clear that.

**Comment by Jassi10000** [comment]
@Namanl2001 No  <code>yarn dep0</code> and <code>yarn dep1</code>  are giving no issues , 
only <code>yarn dev</code> is

**Comment by Jassi10000** [comment]
> Okay you can ask on me on discord. I think its only on your machine that error is coming. Anyways I'll clear that.

Sure , will message you there

**Comment by Namanl2001** [comment]
If your issue is resolved then we can close this. And please mention the solution so that if it is from our side then we can remove that bug.

**Comment by Jassi10000** [comment]
No its not solved yet @Namanl2001 , was lil busy so was not able to connect on discord , today I will definitely do that

**Comment by Jassi10000** [comment]
> can you please try doing ">=12.14.0" [here](https://github.com/Namanl2001/MERN-Gurujii-dev/blob/a453f7994418dd4f74c945ddbb3e14d21429fa27/backend/package.json#L26) and restarting the server.
> BTW have you faced any problem with `yarn dep0` and `yarn dep1` commands?

The engines  already has   >=12.14.0  written on it and then also its not starting

**Comment by Namanl2001** [comment]
- At the root of the project run `yarn start` and take the terminal's screenshot.
- stop this frontend server started above. `ctrl + c`
- move to backend folder `cd backend` and run `yarn start` to take the terminal's screenshot.
- Kindly share both the screenshot's here in comments or discord

**Comment by Jassi10000** [comment]
Ok ,  just sharing in a few minutes

**Comment by Jassi10000** [comment]
This is the screenshot of the <code>yarn start</code> in the root folder 

![guru1](https://user-images.githubusercontent.com/64856348/115191684-64a04480-a107-11eb-9aea-cc5eedab6e16.PNG)


This is the screenshot of the <code>yarn start</code> in the backend folder



![guru2](https://user-images.githubusercontent.com/64856348/115192075-f1e39900-a107-11eb-81e4-5e240035a96a.PNG)

**Comment by Namanl2001** [comment]
Okay so your frontend server is running perfectly.
But problem in backend so for that add the missing package which is being shown on your terminal `yarn add express-rate-limit` then try to start the server. If again there is some problem try running 'yarn dep1' and then restart the server.
Still if there is problem then try deleting node-modules file from your backend dir and run 'yarn dep1' and try starting the server.
If still there is some problem attach the screenshot in comments after try 3rd soln. Else you can run 'yarn dev' from the root to start both frontend and backend server with a single command.

**Comment by Jassi10000** [comment]
Sure , btw Is this problem only faced by me or other contributors as well  ?

**Comment by Namanl2001** [comment]
I didn't get any such problem from other contributors. But sometimes it happens due to different setup environments

**Comment by Jassi10000** [comment]
> I didn't get any such problem from other contributors. But sometimes it happens due to different setup environments

Ohh , anyways leme try this one again

**Comment by Jassi10000** [comment]
@Namanl2001 See there are lot of confusions which are occuring 

These are series of events that happened

1. 
![guru3](https://user-images.githubusercontent.com/64856348/115242453-82899b80-a13f-11eb-96d7-3e40d3ba1c7f.PNG)

2.
![guru4](https://user-images.githubusercontent.com/64856348/115242472-861d2280-a13f-11eb-8697-2971c8418451.PNG)


After this I uninstalled the node modules and  again did <code>yarn dep1</code> , that was successfull 


After this I this <code>yarn dev</code> in the root folder and these 2 are the screenshots of what happened
The frontend is running but the backend is not


3.
![guru5](https://user-images.githubusercontent.com/64856348/115242486-87e6e600-a13f-11eb-87b6-487d6a6c85aa.PNG)

4. 
![guru6](https://user-images.githubusercontent.com/64856348/115242823-e3b16f00-a13f-11eb-9d7d-a00bccca3829.PNG)

**Comment by Namanl2001** [comment]
Everything is OK now you just have to set up the MongoDB connection [Read this](https://github.com/Namanl2001/MERN-Gurujii-dev#note--)

**Comment by Namanl2001** [comment]
If you have any other problem. Feel free to ask them on the discord project channel.
