### ISSUE TITLE
Separate About Us Page

### ISSUE THREAD

**Issue by tend2infinity** [Namanl2001/MERN-Gurujii-dev#156]
**Describe the feature you'd like to add**
Currently, the about us section is visible on top of the teacher cards. We can use one of the navbar links to link the homepage with the about section and make it on a separate page

**Comment by Namanl2001** [comment]
Nice thought but IMO it is not needed because on the separate page we would be showing hardly 8-10 lines about section and the rest of the page will be empty and also it comes with its own challenges of designing and marinating a new webpage. WDYT?

**Comment by tend2infinity** [comment]
See, we have a navbar in which almost all the links are not functional right now, so its just an idea of making use of it. Moreover the about section seems kind of separated from the other part of the page because, if I am a new user then maybe I need to see the about page, but if I become an old user for this application then the about section seems repetitive and unnecessary popping out on every reload...I mean thats what I think

**Comment by tend2infinity** [comment]
If you have any suggestions about the links on the navbar then please tell me, I can start working on that

**Comment by sagar-barapatre** [comment]
About us section can contain all the list of contributors displaying in proper profile cards with a proper quote in the header of it. What say ??

**Comment by tend2infinity** [comment]
I would be happy to work on that if you agree

**Comment by sagar-barapatre** [comment]
Okay let us wait for approval then if it gets approved you can start working

**Comment by Namanl2001** [comment]
Let's do it :)

**Comment by sagar-barapatre** [comment]
Before implementing the design please show us the template of that page. Once it gets approved you can further work on that.

**Comment by ChitvanRamani22** [comment]
@tend2infinity are you working on this?

**Comment by tend2infinity** [comment]
Yup, really sorry for the delay. I'll make the PR by tomorrow positively

**Comment by ChitvanRamani22** [comment]
> Yup, really sorry for the delay. I'll make the PR by tomorrow positively.
@tend2infinity Let me know at the earliest if you change your mind

**Comment by ChitvanRamani22** [comment]
> Yup, really sorry for the delay. I'll make the PR by tomorrow positively

@tend2infinity let me know at the earliest if u change your mind.
