### ISSUE TITLE
UI: contact no. not shown on profile cards.

### ISSUE THREAD

**Issue by Namanl2001** [Namanl2001/MERN-Gurujii-dev#158]
**Describe the bug**
We have contact no. of the tutor and we show it on profile cards but due to some bug, it is shifted somewhere below the cards back.
This issue is just to make small changes in the CSS to have it properly viewed on the cards.

**Comment by Namanl2001** [comment]
proper positioning should be like this -> https://cdn.discordapp.com/attachments/824587831833526292/830475558911213639/20210410_214204.jpg

**Comment by tend2infinity** [comment]
I wanna work on that
