### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by sagar-barapatre** [Namanl2001/MERN-Gurujii-dev#16]
We we'll need to create a contributing.md file in project directory where we can give all the details about how to create an issue with a particular template as well as while creating a PR.

**Comment by khareyash05** [comment]
Hello Sir I would like to work on this issue..

**Comment by khareyash05** [comment]
I have a small doubt , In the file we have to mention how to create an issue and a pull request right?

**Comment by khareyash05** [comment]
Hello Sir! I have created a Pull Request fro the same ..Have a look

**Comment by mohammedjameel24** [comment]
assign me
