### ISSUE TITLE
github action to add autolabel of gssoc on PR 

### ISSUE THREAD

**Issue by Ankita297** [Namanl2001/MERN-Gurujii-dev#160]
**Describe the feature you'd like to add**
github action to add autolabel of gssoc on PR

**Describe how you will do it**
I wan to add github action for that .

**Additional context**

**Comment by Ankita297** [comment]
@Namanl2001 can i work on this ?

**Comment by Namanl2001** [comment]
It's already present, you can see that github action is applied on this issue also. Anything else you would like to improve?

**Comment by Ankita297** [comment]
@Namanl20
![Home_external tutor by akshay1027 · Pull Request #122 · Namanl2001_MERN-Gurujii-dev - Google Chrome 23-04-2021 18_21_21](https://user-images.githubusercontent.com/67833077/115873654-cd1d5780-a460-11eb-9981-21f9e10d2427.png)
01  You are adding it in maually in the PR

**Comment by Ankita297** [comment]
@Namanl2001 ?

**Comment by Namanl2001** [comment]
Oh sorry I mistook as adding the label on the issue. But you are talkong about PR.
Btw on what basis it would be added on prs? Will it be added on all future prs of any kind?

**Comment by Ankita297** [comment]
@Namanl2001 it will added on all future PRs .

**Comment by Namanl2001** [comment]
But we don't want that action as we'd have to remove it after 1 one month when gsspc ends? IMO

**Comment by Ankita297** [comment]
![Gurujii com - Google Chrome 27-04-2021 22_35_06](https://user-images.githubusercontent.com/67833077/116282864-e861cd00-a7a8-11eb-9a7c-1c1a1661abc6.png)

**Comment by Ankita297** [comment]
@Namanl2001 @sagar-barapatre  Can this be used  ?

**Comment by sagar-barapatre** [comment]
Yeah we can try this. what say @Namanl2001 ?

**Comment by Ankita297** [comment]
@Namanl2001 ?

**Comment by Namanl2001** [comment]
Sorry, but we don't need this.
