### ISSUE TITLE
Add a welcome bot 

### ISSUE THREAD

**Issue by Ankita297** [Namanl2001/MERN-Gurujii-dev#161]
**Describe the feature you'd like to add**
Add github action to greet contributor on his /her first issue and PR creation .
**Describe how you will do it**
A clear and concise description of how you will do it.

**Additional context**

**Comment by Ankita297** [comment]
@Namanl2001  can i work on this ?

**Comment by Namanl2001** [comment]
Can you describe a bit more about the change you are suggesting? Greeting in what sense?

**Comment by Ankita297** [comment]
@Namanl2001   like when contributor  make his first issue or first PR  message will be shown 
![New issue · Issue #1 · Ankita297_Story - Google Chrome 22-04-2021 00_53_11](https://user-images.githubusercontent.com/67833077/115873148-3cdf1280-a460-11eb-8981-eb9cd3cac553.png)

**Comment by Namanl2001** [comment]
Go ahead with this. thanks
