### ISSUE TITLE
Pre-Loader

### ISSUE THREAD

**Issue by ChitvanRamani22** [Namanl2001/MERN-Gurujii-dev#166]
I want to add preloader to the website.
I will use suspense,lazy to fetch and show preload until all the data is being loaded.
@Namanl2001 please assign this to me.

**Comment by Namanl2001** [comment]
Pre-loader is already implemented. Please check this https://github.com/Namanl2001/MERN-Gurujii-dev/pull/147

**Comment by ChitvanRamani22** [comment]
@Namanl2001 i am talking about something like this.
https://user-images.githubusercontent.com/76901313/114297933-46b45d80-9ad1-11eb-9633-be4359257b9d.mp4

**Comment by Namanl2001** [comment]
PHAL @ https://github.com/Namanl2001/MERN-Gurujii-dev/issues/132
