### ISSUE TITLE
Enhancement of 404 Page

### ISSUE THREAD

**Issue by ShubhamSj07** [Namanl2001/MERN-Gurujii-dev#170]
**Describe the feature you'd like to add**
We are shown 404 page on invalid route but rather showing just a 404 img, we should be redirecting user to home page via btn.

Page looks like this,
![MERN-Guruji-Issue-original](https://user-images.githubusercontent.com/56510414/116862694-c641d200-ac22-11eb-9f41-c7cb87dbe46c.JPG)

on mobile view,
![MERN-Guruji-Issue-original--](https://user-images.githubusercontent.com/56510414/116862748-d954a200-ac22-11eb-8f95-19e9d1113fb3.JPG)

I would like to enhance it like,
I have made two themes, if in future dark-mode get integrated would have some ref.
![MERN-Guruji-Issue](https://user-images.githubusercontent.com/56510414/116862808-ec677200-ac22-11eb-8849-e5033cfd433e.JPG)
![MERN-Guruji-Issue--choice2](https://user-images.githubusercontent.com/56510414/116862861-05702300-ac23-11eb-8638-094bce732121.JPG)

Small Screen views,
![MERN-Guruji-Issue--FIXED](https://user-images.githubusercontent.com/56510414/116862915-1ae54d00-ac23-11eb-9fb1-fd1902e2efb4.JPG)
![MERN-Guruji-Issue--choice2--FIXED](https://user-images.githubusercontent.com/56510414/116862917-1b7de380-ac23-11eb-961a-9b6f256e808c.JPG)

Pls, assign me this issue :)

**Comment by ShubhamSj07** [comment]
@Namanl2001 pls review

**Comment by Namanl2001** [comment]
The home option on the top navbar do this work for us. Anyway we can have a button too as you suggested. Go ahead with your idea. Thanks
