### ISSUE TITLE
Make form responsive

### ISSUE THREAD

**Issue by Namanl2001** [Namanl2001/MERN-Gurujii-dev#173]
We have a double-column form to make profiles, but it's not responsive for tablets/mobiles. The task is to make it responsive for devices of standard resolutions

**Comment by theBeginner86** [comment]
I want to work on this issue, as GSSOC 21 participant.

**Comment by theBeginner86** [comment]
@Namanl2001 
I had a doubt, for the mobile view decreasing just the font size is not helping so will it be ok if I stack the profile form as row (like stacking the left form on the top of the right form using flex properties) rather than column.
