### ISSUE TITLE
Our reach

### ISSUE THREAD

**Issue by ChitvanRamani22** [Namanl2001/MERN-Gurujii-dev#174]
Want to add our reach section as shown in the image below just above footer to make homepage look more attractive.
![20210503_163243.jpg](https://user-images.githubusercontent.com/68965499/117112552-db476e00-ada6-11eb-958e-e7ca76767231.jpg)
@Namanl2001 @sagar-barapatre please assign this to me.

**Comment by Namanl2001** [comment]
Will the data be hard-coded? or will you fetch it using some Github API?

**Comment by ChitvanRamani22** [comment]
@Namanl2001 it will be hard-coded as we have plus sign after the number.

**Comment by sagar-barapatre** [comment]
As @ChitvanRamani22 is saying it will be hard-coded. Everytime whenever the stats get changes people will make new PR.

**Comment by ChitvanRamani22** [comment]
>  As @ChitvanRamani22 is saying it will be hard-coded. Everytime whenever the stats get changes people will make new PR. 

@sagar-barapatre we have a plus sign after each value so it is not necessary to change them after their values get changed.
