### ISSUE TITLE
Implement teacher's popularity among users

### ISSUE THREAD

**Issue by Namanl2001** [Namanl2001/MERN-Gurujii-dev#181]
On the card's backside, we have a `click here to read more button; we can use this to monitor the popularity of the teacher.
When a user clicks on this, we'll make a post request and increase the counter by 1 in the backend—more the clicks, more the counter, and more the popularity.

Further, we can use this to add a filter by popularity and can also show the number of clicks on the card itself for each user.

This work can be done in separate PR's.

**Comment by tend2infinity** [comment]
interested

**Comment by subhangi2731** [comment]
@Namanl2001 please assign me this issue

**Comment by sagar-barapatre** [comment]
Assigned this to you.

**Comment by Namanl2001** [comment]
@tend2infinity would be nice if you do this before documentation issue. Thanks

**Comment by subhangi2731** [comment]
@Namanl2001 how can u unassign me without even informing I have done almost half of this work

**Comment by Namanl2001** [comment]
Because you've been assigned too many issues, on some you said you'll open a pr the very next day but now I guess it's a week and there is still no response on any of them. 

Anyways, you can complete your half done work and open a PR.

Sorry for the inconvenience caused.

**Comment by tend2infinity** [comment]
Yeah sure! @Namanl2001 I'll focus on this one

**Comment by subhangi2731** [comment]
@Namanl2001 I have already completed this should I create pr please assign me
