### ISSUE TITLE
Toast messeges.

### ISSUE THREAD

**Issue by ChitvanRamani22** [Namanl2001/MERN-Gurujii-dev#193]
Alert pop ups do not look good . I would like to add toast messeges instead of alerts.
@Namanl2001 please assign this to me.

**Comment by Namanl2001** [comment]
PHAL @ https://github.com/Namanl2001/MERN-Gurujii-dev/issues/152#issuecomment-821807984

**Comment by ChitvanRamani22** [comment]
@Namanl2001 but i want to add it at a time when the form is submitted successfully.

**Comment by ChitvanRamani22** [comment]
@Namanl2001 but toast messeges would do same function as alerts do.

**Comment by Namanl2001** [comment]
Okay, so form submitted means user's profile is created successfully right? And then in order to fetch the details we need to reload the webpage to show the newly added user on a new card.
Is the reload possible with toast messages?

**Comment by ChitvanRamani22** [comment]
@Namanl2001 i will do that and let you know.

**Comment by Namanl2001** [comment]
Sure you can try it
