### ISSUE TITLE
Units Tests for backend

### ISSUE THREAD

**Issue by Namanl2001** [Namanl2001/MERN-Gurujii-dev#20]
Unit testing involves testing individual components of the software program or application. The main purpose behind this is to check that all the individual parts are working as intended. A unit is known as the smallest possible component of software that can be tested. 
The task would be to add unit tests for the backend, you can prefer jest to write your unit tests. This issue can be resolved using multiple PR's. And multiple people can work on this, so directly asking for assigning it to you, have a look in the backend codebase to find the component, for which you would like to add the unit test. And also verify in the comment section below to check if anyone working on it already to prevent duplicate efforts. I'll not be assigning this issue to anyone individually, if no one is working on that component feel free to take it up and make a PR, but before starting don't forget to mention it in the comments. Points will be awarded on the basis of PR(s).
Thanks.

**Comment by promaroy** [comment]
Can I take up this issue as a part of GSSOC '21?

**Comment by Namanl2001** [comment]
@promaroy do you have some prior knowledge of writing unit tests? If yes lemme know, I shall assign it to you.

**Comment by ApekshaAgarwal** [comment]
@Namanl2001 , can I contribute on this issue. I have written units test cases in Jest.

**Comment by Namanl2001** [comment]
yes you can @ApekshaAgarwal

**Comment by Sukriti-sood** [comment]
Hey @Namanl2001  Is this Issue Open? , I have written test using mocha and chai but interested in writing in Jest , I have gone through backend code , I want to write test for user related functions

**Comment by Namanl2001** [comment]
Yes this issue is open you can go ahead 👍

**Comment by sagar-barapatre** [comment]
@Sukriti-sood what your is current work status ?

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood what your is current work status ?

I was getting some errors while using jest , I was trying to resolve them , if can't will ask and try to complete soon.

**Comment by Sukriti-sood** [comment]
Please help me , I am getting this error, I tried but can't figure out
![Screenshot from 2021-04-28 15-44-32](https://user-images.githubusercontent.com/55010599/116388355-5eae1000-a839-11eb-902f-e3903ec81432.png)

**Comment by subhangi2731** [comment]
@Namanl2001 please assign me this issue i want to work on this

**Comment by sohan2410** [comment]
There is no deleteAnswer controller in `backend/controllers/admin.controller.js`, so I am removing this route as server is not starting
