### ISSUE TITLE
Styling 

### ISSUE THREAD

**Issue by Namanl2001** [Namanl2001/MERN-Gurujii-dev#200]
![image](https://user-images.githubusercontent.com/56021229/118823174-657af080-b8d6-11eb-8f44-83879a7fdab0.png)

We would like to have all three dropdowns in one row (center) and `clear filter` button in a separate row below them again in center.

PS: The bug and attached screenshot is for mobile view on wide screens it is fine.

**Comment by ChitvanRamani22** [comment]
@Namanl2001 i want to work on this.

**Comment by Namanl2001** [comment]
closing via #203
