### ISSUE TITLE
Health Tips In Dropdown

### ISSUE THREAD

**Issue by vanshika2906** [Namanl2001/MERN-Gurujii-dev#205]
**Describe the feature you'd like to add**
I would like to add a button in the dropdown that provides students some health tips so that they will be able to focus on their study in a better way and relief them from extra stress.

**Comment by vanshika2906** [comment]
Let me know if this good to go or you want some modifications. I would like to work on this, please assign to me. Thankyou!

**Comment by Namanl2001** [comment]
Sounds good to me. BTW in which section of the webpage you would like to add this feature?
And of which dropdown are you talking about here?

> I would like to add a button in the dropdown

**Comment by vanshika2906** [comment]
> Sounds good to me. BTW in which section of the webpage you would like to add this feature?
> And of which dropdown are you talking about here?
> 
> > I would like to add a button in the dropdown

I am thinking of putting it here or you can suggest where it is good to go?
![image](https://user-images.githubusercontent.com/65587816/119083776-3a9bb400-ba1e-11eb-9368-e33c22e06f2e.png)

**Comment by Namanl2001** [comment]
Are you planning to make a new webpage for this feature?

**Comment by vanshika2906** [comment]
Yes @Namanl2001 , just like the home page by removing about us content and Plan your future with us and putting six cards providing tips for health and providing that web page route in the dropdown. Any suggestions and correction for this thought?
Thankyou!

**Comment by Namanl2001** [comment]
Sounds good to me. Please go ahead 👍
