### ISSUE TITLE
Redesigning the about part.

### ISSUE THREAD

**Issue by ChitvanRamani22** [Namanl2001/MERN-Gurujii-dev#210]
I want to remove the about us page and add something attractive in that place .
@Namanl2001 please assign this to me.

**Comment by ChitvanRamani22** [comment]
@Namanl2001 yes.

**Comment by Namanl2001** [comment]
okay. Also we hill have [this](https://user-images.githubusercontent.com/61948033/119116842-48652f80-ba46-11eb-8a02-672365ec356a.mp4) soon so plan accordingly.
