### ISSUE TITLE
Adding error page 

### ISSUE THREAD

**Issue by anjali1102** [Namanl2001/MERN-Gurujii-dev#212]
**Describe the feature you'd like to add**
When the request fails or get we 404 error, it shows a very ugly page. I will construct a new error page.

**Describe how you will do it**
A clear and concise description of how you will do it.

**Additional context**

WHEN REQUEST FAILS, NOTICE THE URL
![gurujigssoc1](https://user-images.githubusercontent.com/56559378/119250184-ec241c00-bbbb-11eb-8d96-262037e99b37.png)

WHAT I WILL DO
![image](https://user-images.githubusercontent.com/56559378/119250210-1e357e00-bbbc-11eb-8a0b-34403d2b11e0.png)

**Comment by anjali1102** [comment]
Kindly assign me this issue

**Comment by ChitvanRamani22** [comment]
@anjali1102 This website already has a well designed error page which looks like this.
![20210523_122328.jpg](https://user-images.githubusercontent.com/68965499/119251016-b97d2200-bbc1-11eb-8f57-b55aa40fc17a.jpg)

**Comment by Namanl2001** [comment]
Thanks @anjali1102 for noticing but as @ChitvanRamani22 said it's already present in our development mode and is not pushed to production yet. Will do it soon.
