### ISSUE TITLE
Add Welcome Bot

### ISSUE THREAD

**Issue by vanshika2906** [Namanl2001/MERN-Gurujii-dev#217]
**Describe the feature you'd like to add**
I would like to add a GitHub action, got appeared when someone creates a issue.
Saying something like this
"Thank you for opening an issue.
 To get assigned to this particular issue please wait for maintainers."
I would like to work on this. Please assign this to me.

**Comment by Namanl2001** [comment]
This feature is already present for first time issues [like this](https://github.com/Namanl2001/MERN-Gurujii-dev/issues/205#issuecomment-845354706).
Adding this note for each issue would be a good?

**Comment by vanshika2906** [comment]
I have seen this feature in many projects that's why I suggested. Although if don't want for every issue, can create for Pull Request which I just saw not present. Thankyou!!

**Comment by ChitvanRamani22** [comment]
@vanshika2906 are you working on this??

**Comment by Namanl2001** [comment]
closing via #225
