### ISSUE TITLE
Project installation difficulties

### ISSUE THREAD

**Issue by Muditxofficial** [Namanl2001/MERN-Gurujii-dev#26]
First of all documentation is not at all good, give details about the ./config file.
Following is a error i encountered,
![Screenshot from 2021-03-09 21-57-57](https://user-images.githubusercontent.com/63860014/110504163-e5404e00-8122-11eb-8f91-c14ae95c6fb9.png)

**Comment by Namanl2001** [comment]
For security reasons I have made the MongoDb URI secure, by not adding hardcoded username and password. For development purpose you can install, mongodb locally or use the online version.
Will update this in the docs soon. Thanks.
