### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by sagar-barapatre** [Namanl2001/MERN-Gurujii-dev#3]
When The server is down, we can create a 404 page displaying in the UI that it's internal problem and show that with a proper user interface.

**Comment by Aniket1103** [comment]
I would like to work on this issue, can u please assign it to me?

**Comment by khareyash05** [comment]
Hello Sir! I would like to work on this issue as a part of GSSOC'21.

**Comment by vkassingh** [comment]
@Namanl2001 i would like to contribute to the project guruji. do we have a group for the discussion?

**Comment by Namanl2001** [comment]
Thanks @vkassingh for your kind interest. We will soon have the discussion group, stay tuned ✌.

**Comment by sayna3311** [comment]
I would love to work on this issue, under GSSoC'21 :)

**Comment by Namanl2001** [comment]
feel free to take this up @sayna3311 . Thanks!

**Comment by sayna3311** [comment]
@Namanl2001 please assign this to me.

**Comment by nikitakapoor1919** [comment]
Can I also work under this issue? @Namanl2001. Please Assign this task to me also.

**Comment by sagar-barapatre** [comment]
Hey @sayna3311 start working on this...As you are assigned to this
Rest people over here will review your PR

**Comment by sayna3311** [comment]
I am having some issues while setting up the project, like not able to connect frontend with backend. I have somewhat made the 404page. Where can I get my doubt cleared?

**Comment by Namanl2001** [comment]
@sayna3311 project channel will be open for all participants soon. Till then you can ask your queries here only to @sagar-barapatre (he is one of the mentors for this project).

**Comment by sagar-barapatre** [comment]
Yeah @sayna3311 you can ask. What issues are you facing ?

**Comment by sayna3311** [comment]
I tried to run this using npm start as yarn dev wasn't working for me.
![image](https://user-images.githubusercontent.com/67572440/110654537-39f7cd80-81e4-11eb-829c-1a46be154711.png)
![image](https://user-images.githubusercontent.com/67572440/110654592-47ad5300-81e4-11eb-85ab-50fa15dcdc64.png)
I am not able to set up the project locally.
@sagar-barapatre

**Comment by nikitakapoor1919** [comment]
@sayna3311 I can help as i have faced similar issues.
For security reasons sir had made the MongoDb URI secure, by not adding a hardcoded username and password. For development purpose, you can install, MongoDB locally or use the  online version.
So this means there is no config file in our backend.
Kindly comment these lines in server.js. and user.js  and create your own url from https://cloud.mongodb.com/
### server.js
![image](https://user-images.githubusercontent.com/62166533/110657566-ef2b8500-81e6-11eb-938e-dea125e99b24.png)

### user.js
![image](https://user-images.githubusercontent.com/62166533/110657860-33b72080-81e7-11eb-8306-3fbe0ac44af6.png)

**Comment by Namanl2001** [comment]
@nikitakapoor1919 can you please also update this info in your current readme.md pr, regarding which lines to comment? You could add this as the 3rd point of the note.
Just add the line Numbers, along with file name.

**Comment by nikitakapoor1919** [comment]
@Namanl2001 Okay I will do that.

**Comment by Ankita297** [comment]
Can i work on this @Namanl2001

**Comment by sagar-barapatre** [comment]
@Ankita297 Off course you can. Assigning it to you.
