### ISSUE TITLE
Header Improvement

### ISSUE THREAD

**Issue by deeptea22** [Namanl2001/MERN-Gurujii-dev#31]
Would like to improve the header and make it static, as its not visible when scrolling down. Please assign this to me under GSSOC'21. Thanks :)

**Comment by deeptea22** [comment]
@Namanl2001 I am facing issues setting up the project locally. Could you please guide me on how to do it?.

**Comment by Namanl2001** [comment]
As we have some recent changes please follow these steps 
- pull the recent changes
- follow instructions in readme.md and comribution.md

if you still face any problem feel free to ask.

**Comment by deeptea22** [comment]
I am having trouble installing the dependencies. When i give the command:
' $ cd backend yarn install '
It shows an error: ' cd: too many arguments '

**Comment by Namanl2001** [comment]
break it into two steps 
'cd backend' 
'yarn install'
and check which command is creating problem.
You can always Google search your problem.

**Comment by mansijain980** [comment]
@Namanl2001 Is this issue solved? if not , i want to solve it .
Thanks.

**Comment by mansijain980** [comment]
@Namanl2001 Most Probably i will commit a PR tomorrow.

**Comment by Namanl2001** [comment]
@mansijain980 What's the status? Have you opened a PR?

**Comment by mansijain980** [comment]
> @mansijain980 What's the status? Have you opened a PR?

yes sir , it has almost completed  , only some background part is left ...
Actually my xams r going on bt i will submit it soon.

**Comment by guptaji6489** [comment]
> @Namanl2001 sir , u can assign it to others as due to xams it will take some time .
> If till then , issue not assigned to anyone , then i will proceed it after xams.
> Thanks.

take your time

**Comment by ChitvanRamani22** [comment]
@Namanl2001 i would like to take this up.

**Comment by Ankita297** [comment]
Can i work on this @Namanl2001 @sagar-barapatre ?

**Comment by sagar-barapatre** [comment]
@ChitvanRamani22 are you doing this ?

**Comment by ChitvanRamani22** [comment]
@sagar-barapatre you can assign this to @Ankita297
