### ISSUE TITLE
Add Mr. & Mrs. option.

### ISSUE THREAD

**Issue by ChitvanRamani22** [Namanl2001/MERN-Gurujii-dev#34]
I found one problem, that Mr is appearing before the name of the person, teacher can be female also. So we can make a selection dropdown with two options male/female before the name input field. If its fine could you assign this to me.

**Comment by Namanl2001** [comment]
Yeah it is under my agenda. We will need a mr, mrs. option in form, store it in backend and then show accordingly on the profile cards.
Could you do all these tasks?

**Comment by ChitvanRamani22** [comment]
Yes @Namanl2001 I will try my best . Please assign this to me.

**Comment by HarshitPandey251** [comment]
I want to work on this issue

**Comment by Namanl2001** [comment]
closing via #50
