### ISSUE TITLE
Navbar 

### ISSUE THREAD

**Issue by guptaji6489** [Namanl2001/MERN-Gurujii-dev#35]
We have to make the navbar more attractive. its looks very old.
Like we have to use bootstrap and CSS and javascript more on that.

**Comment by khareyash05** [comment]
Hey can I work on this issue?

**Comment by pi-squared-4** [comment]
I am a GSSOC'21 participant, can you assign this to me? I would love to work on this.

**Comment by Namanl2001** [comment]
assigning this to @pi-squared-4 as @khareyash05 you are already assigned to few othee issues. Thanks

**Comment by pi-squared-4** [comment]
Alright, I'll share soon.

**Comment by pi-squared-4** [comment]
Hey guys, do you plan to keep this grey-ish theme to your site? Looks a bit dull to me.

**Comment by pi-squared-4** [comment]
If you can finalize a color scheme so that all the styling can be done accordingly? 

![image](https://user-images.githubusercontent.com/66795444/110815485-7ee93600-82b0-11eb-9765-a62b806f6faf.png)

I was thinking of something like this, I have not added the google button, but roughly like this.

**Comment by guptaji6489** [comment]
I think someone is working in Logo also.
make sure the logo must be the same and the design is good.

**Comment by pi-squared-4** [comment]
Okay, let me contact the logo guy.

**Comment by shobit1337** [comment]
I guess this issue is still pending.. I would like to work on this one, Let me know If I can, Thanks 😄

**Comment by sagar-barapatre** [comment]
@shobit1337 what's the status of your work ?

**Comment by shobit1337** [comment]
> 
> 
> @shobit1337 what's the status of your work ?

I'm having hard time understanding the redux part.. Will give update by tonight on discord group.

**Comment by Ankita297** [comment]
Can i work on this @sagar-barapatre @Namanl2001 ?

**Comment by sagar-barapatre** [comment]
@Ankita297 before working on that, provide us with your design template. So that once it gets approved you can work further

**Comment by Ankita297** [comment]
@sagar-barapatre  i will try to make navbar stick to top so that when you scroll down it shows  and i will also work on the ui enhancement  .

**Comment by Ankita297** [comment]
okay @sagar-barapatre .
