### ISSUE TITLE
Removing arrows and adding lower limit for Filter PIN code input

### ISSUE THREAD

**Issue by ssaksham** [Namanl2001/MERN-Gurujii-dev#39]
Hey, I am Saksham Sharma, a GSSOC'21 participant. I am passionate about Data Structures and a full stack developer.
I think it would make more sense to remove arrows from the Filter Pin code input as it would be difficult for anyone to look for a 6 digit PIN code just by using the arrows.
Also, the lower limit of the input is not added, I want to fix that too.

Please assign this task to me.

@Namanl2001

**Comment by Namanl2001** [comment]
FYI It's not mandatory to use arrows for pin code input. User can direct enter the code using keyboard.
Currently lower limit is 100000, so what limit change would you make?

**Comment by ssaksham** [comment]
![image](https://user-images.githubusercontent.com/41958505/110661220-58f95e00-81ea-11eb-9be6-a9761a0e6b87.png)

I want to say it would be difficult for anyone to use arrows to reach a 6 digit PIN code, so it would more convenient to remove the arrows from the input.
Also, please let me know how it is taking values lesser than 100000 or even negative values. 
Even if it is accepting invalid values, it should give a warning of invalid input. Can I work on this too?

**Comment by ssaksham** [comment]
Thanks

**Comment by ssaksham** [comment]
Can I make two separate PR for both issues?

**Comment by Namanl2001** [comment]
As this issue is related only to a single component, I'd ask you to keep your changes in a single PR

**Comment by ssaksham** [comment]
okay

**Comment by Namanl2001** [comment]
Long time no response! should this be assigned to someone else?

**Comment by ssaksham** [comment]
Actually I was facing some issues in setting up the mongodb server, I will try to make PR by tomorrow.

**Comment by ssaksham** [comment]
@Namanl2001  I am not able to connect mongodb even after following the instructions mentioned in the readme.md .
Please help me in connecting the mongodb with the project.

**Comment by ChitvanRamani22** [comment]
@Namanl2001 Could you please assign this to me.

**Comment by Namanl2001** [comment]
@ssaksham mentors could help you in the discord project's channel.
@ChitvanRamani22 let's wait for saksham, to prevent duplicate efforts.

**Comment by ssaksham** [comment]
okay @Namanl2001

**Comment by ssaksham** [comment]
@Namanl2001  Nobody replied on the discord project's channel. I have also DM the mentors but there also received no response.

**Comment by ssaksham** [comment]
@Namanl2001 ??

**Comment by sagar-barapatre** [comment]
Yeah @ssaksham do you need some help ?
