### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by guptaji6489** [Namanl2001/MERN-Gurujii-dev#40]
We have to change or Rebuild Footer its looks very simple.
We have to make it attractive and add some links and tags and much more.
Please have a look on it.

**Comment by Namanl2001** [comment]
What kind of details could be added at the footer? We don't have any office 😅 also no social media handle.

**Comment by Namanl2001** [comment]
We also don't have the logo.

**Comment by Namanl2001** [comment]
@guptaji6489 do you have any suggestion regarding footer? What could be added?

**Comment by guptaji6489** [comment]
![Screenshot (523)](https://user-images.githubusercontent.com/46419188/110666720-96acb580-81ef-11eb-99ba-89b374cb35c4.png)

Ya, we can make it like this.
On the left side, we can put there something about gurujii.
In right-side link, we can put like link1 will replace by Chemistry, the link2 will replace by Physics.... like this
and we can remove the middle one.
And the bootstrap we have to use.

**Comment by Namanl2001** [comment]
And where will the subject links redirect us?

**Comment by guptaji6489** [comment]
Ok, leave it. we can make it like this which is in grey color only

**Comment by dsnehasish74** [comment]
@Namanl2001 Can I work on this as a part of GSSOC21

**Comment by guptaji6489** [comment]
> @Namanl2001 Can I work on this as a part of GSSOC21

Ya sure.
@Namanl2001 assign this to @dsnehasish74

**Comment by dsnehasish74** [comment]
![Screenshot (511)](https://user-images.githubusercontent.com/58779604/110746172-681bf280-8262-11eb-89ba-0cc6a1188ca1.png)
I made the footer like the above example. Should I add more things Please anyone guide or any suggestion?

**Comment by guptaji6489** [comment]
Someone is making logo you can also put a logo.

**Comment by ShambhaviSharma0110** [comment]
Hey, I'm interested in this project could you please allow me to work on it?

**Comment by guptaji6489** [comment]
Ya you can do and collaborate with @dsnehasish74

**Comment by dsnehasish74** [comment]
Is the logo complited?
