### ISSUE TITLE
Dialog Box UI

### ISSUE THREAD

**Issue by nikitakapoor1919** [Namanl2001/MERN-Gurujii-dev#41]
@Namanl2001 can i work on changing UI of dialog boxes ? Please assign me this task.

![image](https://user-images.githubusercontent.com/62166533/110660265-63672800-81e9-11eb-8fac-32bd747b7b9e.png)
![image](https://user-images.githubusercontent.com/62166533/110660289-68c47280-81e9-11eb-9039-c90b279dcaef.png)

**Comment by Namanl2001** [comment]
Yes, you can change the delete profile dialog box. But soon we would be having a double coloumn input form. So once it's ready you could do the change in that too.
You could open a seperate PR for both.

**Comment by sagar-barapatre** [comment]
May be can we implement multi page forms to register a teacher. 
Look at this [Click Here](https://codepen.io/sagar-barapatre/pen/NWbebXM). Can we implement something like this ?
What say @Namanl2001 @nikitakapoor1919 ?

**Comment by nikitakapoor1919** [comment]
@sagar-barapatre It looks good to me.

**Comment by Namanl2001** [comment]
> May be can we implement multi page forms to register a teacher. 
> Look at this [Click Here](https://codepen.io/sagar-barapatre/pen/NWbebXM). Can we implement something like this ?
> What say @Namanl2001 @nikitakapoor1919 ?

@sagar-barapatre pitch your idea here https://github.com/Namanl2001/MERN-Gurujii-dev/issues/8

**Comment by nikitakapoor1919** [comment]
Is there any color theme decided for website? I was thinking we should change color of dialog boxes also.
