### ISSUE TITLE
Add website screenshots in the README.md file

### ISSUE THREAD

**Issue by sagar-barapatre** [Namanl2001/MERN-Gurujii-dev#5]
We can add screenshot so that user can get to know the website actually looks like

**Comment by mohdarif8299** [comment]
I would like to work on this Issue @sagar-barapatre.

**Comment by ChitvanRamani22** [comment]
can I work on this issue! @sagar-barapatre

**Comment by Namanl2001** [comment]
Sorry @mohdarif8299 for some delay.
If you are still interested to work on this issue, feel free to take this up; otherwise please inform us so that we can assign it to someone else.

**Comment by Muditxofficial** [comment]
@Namanl2001 @sagar-barapatre I would like to work on it, so kindly assign it to me but i also found concurrently package to be missing due to which my dev server fails to start. I don't know why your hosted app works or i don't know something.

**Comment by Muditxofficial** [comment]
@Namanl2001 assign this to me and i also have some questions regarding the project setup to ask about.

**Comment by Muditxofficial** [comment]
i have a suggestion instead of pics maybe we use gif which is basically full functionality of website under 20-30sec.

**Comment by Namanl2001** [comment]
yeah it would be more clear. Go with it.
