### ISSUE TITLE
Add home tutor and  external tutor options

### ISSUE THREAD

**Issue by Rimpi246** [Namanl2001/MERN-Gurujii-dev#51]
**Add  home tutor and external tutor options**
Tutions may be  at home also and outside also.So there should be two options: one for home tutor and one for tution at another space.
I would like to work on this as a part of GSSOC'21.Please `/assign` this to me

**Comment by Namanl2001** [comment]
Thanks , please go ahead

**Comment by Rimpi246** [comment]
Okay

**Comment by Namanl2001** [comment]
@Rimpi246 are you working on this?

**Comment by ChitvanRamani22** [comment]
@Namanl2001 could you please assign this to me.

**Comment by Namanl2001** [comment]
@ChitvanRamani22 FYI this feature needs to be implemented in both frontend and backend.

**Comment by ChitvanRamani22** [comment]
@Namanl2001 does it mean in the same way as i did in Mr and Mrs option .

**Comment by ChitvanRamani22** [comment]
@Namanl2001 Do I need to mention the selected option(by the user) in the cards as well?

**Comment by Namanl2001** [comment]
> @Namanl2001 Do I need to mention the selected option(by the user) in the cards as well?

Yes.

**Comment by ChitvanRamani22** [comment]
@naman as I updated the repository on my computer there are so many errors in components/form.jsx and components/update.jsx . How should I proceed further.

**Comment by ChitvanRamani22** [comment]
blob:file:///a2e238c0-d06b-44a2-a139-250a7347ce1c

**Comment by ChitvanRamani22** [comment]
blob:file:///96440a33-e12d-4917-8d4a-683b582e21b8

**Comment by ChitvanRamani22** [comment]
![a2e238c0-d06b-44a2-a139-250a7347ce1c](https://user-images.githubusercontent.com/68965499/111975339-7ef5fb00-8b26-11eb-9b37-0418ae1979b2.jpg)
![96440a33-e12d-4917-8d4a-683b582e21b8](https://user-images.githubusercontent.com/68965499/111975398-903f0780-8b26-11eb-8cda-db961d9d4e03.jpg)

**Comment by Namanl2001** [comment]
@ChitvanRamani22 mentors could help you with this in disord channel.

**Comment by ChitvanRamani22** [comment]
@naman to whom should i address my concern?

**Comment by ChitvanRamani22** [comment]
@Namanl2001 to whom should i address my concern ?

**Comment by Namanl2001** [comment]
> 
> 
> @Namanl2001 to whom should i address my concern ?

with the mentors in project channel

**Comment by ChitvanRamani22** [comment]
@Namanl2001 i have generated the PR today morning.
It is approved by @sagar-barapatre please do check it.

**Comment by ChitvanRamani22** [comment]
@Namanl2001 Sir i have corrected it and created a new pr in a branch named tutorty.

**Comment by Namanl2001** [comment]
closing via #103
