### ISSUE TITLE
Change favicon

### ISSUE THREAD

**Issue by Rimpi246** [Namanl2001/MERN-Gurujii-dev#57]
**I want to add a different favicon for the website.**
Please `/assgn` this to me as a part of GSSOC'21

**Comment by guptaji6489** [comment]
Please do it

**Comment by Vaibhav-afk** [comment]
### I'm interested in fixing this issue .

**Comment by Rimpi246** [comment]
@Vaibhav-afk  I am doing already.You can work on other issues or create your own.

**Comment by Vaibhav-afk** [comment]
@Rimpi246 okay no problem

**Comment by Namanl2001** [comment]
@Rimpi246 5 days and no response from your side. Acc. to gssoc guidelines after 5 days we can assign it to someone else.

**Comment by Vaibhav-afk** [comment]
Yeah! I wanna do , can you assign me?

**Comment by guptaji6489** [comment]
@Rimpi246 you are not replying also.
I'm assigning to @Vaibhav-afk
