### ISSUE TITLE
Adding multiple OAuths for login/signup 

### ISSUE THREAD

**Issue by ritik307** [Namanl2001/MERN-Gurujii-dev#60]
**Adding OAuth for the following:-**

- Google
- Linkedin
- Github
- Facebook.

**Comment by ritik307** [comment]
@Namanl2001 @sagar-barapatre  I am currently working on this issue so please assign me this issue.

**Comment by sagar-barapatre** [comment]
This issue has already been created. 
#24  Hence I am closing this

**Comment by ritik307** [comment]
@sagar-barapatre @Namanl2001  I have already commented there to assign this issue to me but I got no response there. Kindly look into that.
