### ISSUE TITLE
Delete Backend README.md

### ISSUE THREAD

**Issue by Navya-amarneni** [Namanl2001/MERN-Gurujii-dev#64]
The Backend README looks very unclean and is not organized. I have added the features that made it look polished and professional.
Kindly have a look at my PR and assign this issue to me. I have made the changes, please suggest any changes to my PR.
Previous:
![image](https://user-images.githubusercontent.com/47153245/110929912-80693b80-834e-11eb-9b16-1044c89a9ff9.png)

Modified:

![image](https://user-images.githubusercontent.com/47153245/110929935-88c17680-834e-11eb-9f4a-ee73c3522a7c.png)

**Comment by Navya-amarneni** [comment]
@Namanl2001  Task is done.Please merge my PR

**Comment by Namanl2001** [comment]
closing via #65
