### ISSUE TITLE
Validation of create profile form

### ISSUE THREAD

**Issue by Samridhi-98** [Namanl2001/MERN-Gurujii-dev#69]
**Describe the bug**
Create profile form has no validation, also it needs a little UI enhancement like proper spacing between fields.

**Expected behavior**
A form should have proper validation, important fields need to be filled before submission.

**Screenshots**
![form](https://user-images.githubusercontent.com/54466041/111021805-f6c07900-83f4-11eb-9eba-de7547522d90.JPG)

**Comment by Samridhi-98** [comment]
@Namanl2001 @sagar-barapatre I would like to work on this part will you please assign me.

**Comment by sagar-barapatre** [comment]
Wait for this because the profile form UI will be changed in one of the issues. Once it gets changed you can start working after that

**Comment by Samridhi-98** [comment]
Okay.

**Comment by ChitvanRamani22** [comment]
@sagar-barapatre Can I work on this issue.

**Comment by mansijain980** [comment]
@Namanl2001 CAN I WORK ON THIS ISSUE?

**Comment by Ashish2030** [comment]
@mansijain980  Yes you can

**Comment by mansijain980** [comment]
Thanks

**Comment by ChitvanRamani22** [comment]
@Namanl2001/MERN-Gurujii-dev
***@***.***> why
didnt i got assigned even tough i commented first.

**Comment by sagar-barapatre** [comment]
@Samridhi-98 Are you working on this ? Coz it's taking a lot of time fro your side to solve a level 0 issue.
If you are struck somewhere you can ask us.

**Comment by mansijain980** [comment]
@sagar-barapatre sir i m working on this ..and spacing has already done ...inly some things left ....i will also complete them ....actually there is an another issue of header improvement so i m doing that ....bt after that i will surely do this as half work has been completed.
Thanks

**Comment by Samridhi-98** [comment]
@sagar-barapatre I haven't started working on it yet as you asked me to wait for the changes in the form UI i.e issue #8.
PR for this issue is active once it got merged, I will start working on it.

**Comment by sagar-barapatre** [comment]
Anyone interested to take up this ?
