### ISSUE TITLE
Missing rate limiting

### ISSUE THREAD

**Issue by Namanl2001** [Namanl2001/MERN-Gurujii-dev#7]
HTTP request handlers should not perform expensive operations such as accessing the file system, executing an operating system command or interacting with a database without limiting the rate at which requests are accepted. Otherwise, the application becomes vulnerable to denial-of-service attacks where an attacker can cause the application to crash or become unresponsive by issuing a large number of requests at the same time.
A rate-limiting middleware should be used to prevent such attacks.
## Example
The following example shows an Express application that serves static files without rate limiting:
```
var express = require('express');
var app = express();

 app.get('/:path', function(req, res) {
  let path = req.params.path;
  if (isValidPath(path))
    res.sendFile(path);
});
```
To prevent denial-of-service attacks, the `express-rate-limit` package can be used:
```
var express = require('express');
var app = express();

// set up rate limiter: maximum of 25 requests per minute
var RateLimit = require('express-rate-limit');
var limiter = new RateLimit({
  windowMs: 1*60*1000, // 1 minute
  max: 25
});

// apply rate limiter to all requests
app.use(limiter);

app.get('/:path', function(req, res) {
  let path = req.params.path;
  if (isValidPath(path))
    res.sendFile(path);
});
```
Changes to be done in `backend/routes/users.js`

**Comment by khareyash05** [comment]
Hello sir! I would like to work on it as a part of GSSOC'21 team..If there is no one assigned to the same.May I?

**Comment by dsnehasish74** [comment]
I want to work on this as a part of Gssoc21. Please assign this to me

**Comment by subhangi2731** [comment]
can you please assign this issue to me?

**Comment by abhudaym** [comment]
So all we have to do is include the package `express-rate-limit` and use that package one time in `backend/routes/users.js`?

**Comment by Namanl2001** [comment]
correct. But what do you mean by using 'one time'?

**Comment by abhudaym** [comment]
I mean, we only need to write `app.use(limiter);` one time in `backend/routes/users.js`. Am I correct?

**Comment by Namanl2001** [comment]
> 
> 
> I mean, we only need to write `app.use(limiter);` one time in `backend/routes/users.js`. Am I correct?

Yep! and also define `limiter` before using it, as shown in the example.

**Comment by abhudaym** [comment]
Can I work on this issue?

**Comment by Namanl2001** [comment]
Sure! assigning to you

**Comment by abhudaym** [comment]
Is there any way to test if the limiter is working?

I've added this piece of code to `backend/routes/users.js` 
```// Setting up rate limiter
var RateLimit = require("express-rate-limit");
var limiter = new RateLimit({
  windowMs: 1 * 60 * 1000, // 1 minute
  max: 25,
});
// All user routes will be rate limited
app.use("/", limiter);

**Comment by Namanl2001** [comment]
closing via #79
