### ISSUE TITLE
working with mongoose means working with promises

### ISSUE THREAD

**Issue by abhay27chauhan** [Namanl2001/MERN-Gurujii-dev#71]
### Proposal

if you are working with mongoose, means you are working with promises. So, you need to handle promise. This is an easy fix but good for long term. 

I suggest instead of this:

- **mongoose.connect(url, {
  useNewUrlParser: true,
  useCreateIndex: true,
  useUnifiedTopology: true,
});**

You should do this:

`
const connectDB = async () => {

    try{

            const conn = await mongoose.connect(URL, {useNewUrlParser: true, useUnifiedTopology: true});
            console.log(`MongoDB Connected: ${conn.connection.host}`)
    }catch(err){

            console.log(err)
            process.exit(1)
    }
}

connectDB();
`

It is good practice :)

**Comment by abhay27chauhan** [comment]
I am a participant of GSSOC21, so please let me know if this is a valid proposal

**Comment by abhay27chauhan** [comment]
can i create a new folder for database connection, instead of doing it in the same file

**Comment by ApekshaAgarwal** [comment]
Hey @abhay27chauhan , @Namanl2001 , I also want to contribute in updating mongoose calls.
