### ISSUE TITLE
adding a chotbot

### ISSUE THREAD

**Issue by bindu030** [Namanl2001/MERN-Gurujii-dev#75]
Hello! I am a GSSOC'21 participant.

I observed that there is no chatbot in the website which needs to be there as there are lots of benefits of having chatbots like-
client  engagement will be increased
 service will also be increased
Its trending

There could be some person who would be replying the messages or some bot for faqs.
@Namanl2001

**Comment by sagar-barapatre** [comment]
Yeah It's a good idea.

**Comment by Namanl2001** [comment]
@bindu030 are you working on this?

**Comment by Shikhar15606** [comment]
@Namanl2001 can I start working on this issue. Its been a long since the opening of this issue.
