### ISSUE TITLE
Adding various security features

### ISSUE THREAD

**Issue by udaymittal7** [Namanl2001/MERN-Gurujii-dev#76]
Setting various HTTP headers using helmet
Data sanitization against no SQL injection and XSS
Rate limiter so the server won't get overload

If you find it relevant, please assign me.

**Comment by Namanl2001** [comment]
Thanks! there is already a PR for rate-limiter. 
Could you explain a bit about other security features.

**Comment by udaymittal7** [comment]
Helmet is used to set various http headers and http headers can leak sensitive information. It also protects from clickjacking.

NoSQL injection vulnerabilities allow attackers to inject code into commands for databases that don’t use SQL queries, such as MongoDB. I will protect it using express-mongo-sanitize package.

XSS( Cross Site Scripting ) attacks occur when an attacker uses a web application to send malicious code, generally in the form of a browser side script, to a different end user. I will protect it using xss-clean package.

**Comment by Namanl2001** [comment]
Interesting

**Comment by Namanl2001** [comment]
closing via #79
