### ISSUE TITLE
Double column form

### ISSUE THREAD

**Issue by Namanl2001** [Namanl2001/MERN-Gurujii-dev#8]
### Problem
At present we have a single-column form for creating and editing users' profiles but it is quite small to contain all the input fields uniformly.

### Proposal
It would be nice to have a double-column form to take the user inputs.

**Comment by dsnehasish74** [comment]
Want to work on this. Please assign this  to me'

**Comment by subhangi2731** [comment]
Please assign this to me?

**Comment by AakankshaShah** [comment]
can you assign it to me?

**Comment by Samridhi-98** [comment]
@Namanl2001 @sagar-barapatre Since, this issue has no active PR yet I would like to work on this, will you please assign me this issue.

**Comment by Namanl2001** [comment]
Let's wait for @AakankshaShah if she doesn't respond within a day, will assign it to you @Samridhi-98

**Comment by AakankshaShah** [comment]
@Namanl2001  Yes sir I am working on it hopefully i will finish it in 2 days

**Comment by Namanl2001** [comment]
closing via #95
