### ISSUE TITLE
adding banner to readme

### ISSUE THREAD

**Issue by aditisneh** [Namanl2001/MERN-Gurujii-dev#83]
@guptaji6489  @Namanl2001, I will design some banner for guruji title. Assign me this issue if possible

**Comment by aditisneh** [comment]
![guruji_gif](https://user-images.githubusercontent.com/56735634/111357089-feab4200-86ae-11eb-83ab-5f766cc35932.gif)
This is a gif

**Comment by aditisneh** [comment]
![guruji_gif (1)](https://user-images.githubusercontent.com/56735634/111357679-885b0f80-86af-11eb-8306-1b92b8c3d111.png)
This can be our png banner for guruji. @guptaji6489 @Namanl2001

**Comment by aditisneh** [comment]
![guruji_gif (1)](https://user-images.githubusercontent.com/56735634/111357786-a1fc5700-86af-11eb-8ccb-065fd6613261.gif)
Or else this gif form

**Comment by guptaji6489** [comment]
This gif is looking good

**Comment by aditisneh** [comment]
@Namanl2001 @guptaji6489 shall i make a PR then?

**Comment by guptaji6489** [comment]
yes

**Comment by aditisneh** [comment]
@guptaji6489 created a PR. Do check. Thank you

**Comment by Ashish2030** [comment]
@aditisneh  nice work

**Comment by aditisneh** [comment]
@Ashish2030 thanks :)

**Comment by Namanl2001** [comment]
closing via #93
