### ISSUE TITLE
Incorrect instructions in readme

### ISSUE THREAD

**Issue by singhayushh** [Namanl2001/MERN-Gurujii-dev#86]
**Describe the bug**
While working on a feature, I was following instructions in the readme to run the app locally. The repository's readme mentions under the note section that:
> For security reasons we have made the MongoDb URI secure, by not adding a hardcoded username and password. For development purpose, you can install, MongoDB locally or use the online version.
> Comment line number 6,7,22 in backend/server.js.

After PR #77, there were changes in the server.js file and line 6, 7, 22 point to incorrect locations and commenting out these three lines cause a whole lot of bugs.

**Expected behavior**
The documentation should be updated with the lines to be commented out.

**Additional suggestion**
Many repositories provide with e .env.example or .config.example file where there are placeholders or keys listed, whose values can be then be provided privately by individual contributors rather than ignoring the environment and configuration variables totally.

**Comment by NamamiShanker** [comment]
I agree with the Additional Suggestion @singhayushh . As a participant of GSSOC, can I work on correction and implementation of this @Namanl2001

**Comment by Namanl2001** [comment]
Great suggestions @singhayushh would you like to work on this?

**Comment by singhayushh** [comment]
Yes, I'm willing to!
