### ISSUE TITLE
Randomization in profiles

### ISSUE THREAD

**Issue by Namanl2001** [Namanl2001/MERN-Gurujii-dev#9]
### Problem
Currently, the profiles of teachers who registered recently, are shown at the last.
### Proposal
It would be nice to have some randomization in the data fetched from the backend, and then show it on frontend.

**Comment by khareyash05** [comment]
Hello Sir! I would like to work on this issue as a part of GSSOC'21 if no one is assigned till now

**Comment by Namanl2001** [comment]
assigning to you @khareyash05 !
Thanks

**Comment by vtejaeta** [comment]
I would love to work on this issue @Namanl2001 as a part of GSSOC'21 program

**Comment by Namanl2001** [comment]
Thanks! @vtejaeta , you can work on this issue.

**Comment by vtejaeta** [comment]
Thanks

**Comment by dsnehasish74** [comment]
Can I work on this as a part of Gssoc21

**Comment by vtejaeta** [comment]
I have solved your issue and created a PR as well, when you have
free time,can you please review it?

Thank you
